In [ ]:
import torch


In [ ]:
import numpy as np


In [ ]:
my_torch9 = torch.arange (12)
my_torch9

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
my_torch9 = my_torch9.reshape (4,3)
my_torch9

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
my_torch9 [:,1]
my_torch9

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
my_torch9 [:,2]
my_torch9

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
my_torch9 = my_torch9.reshape (-1,2)
my_torch9

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
my_torch9 [:,1]
my_torch9

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
my_torch9[:,1]
my_torch9

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,0])
tensor_a + tensor_b

tensor([ 7,  9, 11, 13,  5])

In [ ]:
tensor_a - tensor_b

tensor([-5, -5, -5, -5,  5])

In [ ]:
tesnor_a * tensor_b

NameError: name 'tesnor_a' is not defined

In [ ]:
tensor_a * tensor_b

tensor([ 6, 14, 24, 36,  0])

In [ ]:
tensor_a / tensor_b

tensor([0.1667, 0.2857, 0.3750, 0.4444,    inf])

In [ ]:
tensor_b / tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500, 0.0000])

In [ ]:
(tensor_a * tensor_b) / (tensor_a)


tensor([6., 7., 8., 9., 0.])

In [ ]:
tensor_b [5] = 10
tensor_b

IndexError: index 5 is out of bounds for dimension 0 with size 5

In [ ]:
tensor_b[4] = 10
tensor_b

tensor([ 6,  7,  8,  9, 10])

In [ ]:
tensor_a *2
tensor_a

tensor([1, 2, 3, 4, 5])

In [ ]:
tensor_a * 2

tensor([ 2,  4,  6,  8, 10])

In [ ]:
tensor_b * 100

tensor([ 600,  700,  800,  900, 1000])

In [ ]:
(tensor_b + tensor_a)/(tensor_a)


tensor([7.0000, 4.5000, 3.6667, 3.2500, 3.0000])

In [ ]:
torch.add(tensor_a + tensor_b)


TypeError: add() received an invalid combination of arguments - got (Tensor), but expected (Tensor input, Tensor other, *, Number alpha, Tensor out)

In [ ]:
torch.add (tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [ ]:
torch.subtract(tensor_b, tensor_a)

tensor([5, 5, 5, 5, 5])

In [ ]:
torch.multiply(tensor_a, tencor_b)

NameError: name 'tencor_b' is not defined

In [ ]:
torch.multiply(tensor_a, tensor_b)


tensor([ 6, 14, 24, 36, 50])

In [ ]:
torch.divide(tensor_b, tensor_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [ ]:
torch.divide(tensor_a, tensor_b)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [ ]:
tensor_b % tensor_a

tensor([0, 1, 2, 1, 0])

In [ ]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4, 5])

In [ ]:
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [ ]:
tensor_a

tensor([1, 2, 3, 4, 5])

In [ ]:
tensor_b

tensor([ 6,  7,  8,  9, 10])

In [ ]:
torch.pow(tensor_b, tensor_a)

tensor([     6,     49,    512,   6561, 100000])

In [ ]:
#tensor_a=tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([ 7,  9, 11, 13, 15])

In [ ]:
tensor_b.add_(tensor_a)
tensor_b

tensor([13, 16, 19, 22, 25])

In [ ]:
tensor_a
tensor_b

tensor([13, 16, 19, 22, 25])

In [ ]:
tensor_a

tensor([ 7,  9, 11, 13, 15])

In [ ]:
tensor_a.add_(torch.arange(5))
tensor_a

tensor([ 7, 10, 13, 16, 19])

In [ ]:
tensor_a.add_(torch.tensor(1,1,1,1,1))
tensor_a

TypeError: tensor() takes 1 positional argument but 5 were given

In [ ]:
tensor_a.add_(torch.tensor([1,1,1,1,1]))
tensor_a

tensor([ 8, 11, 14, 17, 20])

In [1]:
tensor_a

NameError: name 'tensor_a' is not defined

In [2]:
import torch
import numpy as np


In [3]:
tensor_a = torch.arange(5)

In [4]:
tensor_a

tensor([0, 1, 2, 3, 4])

In [5]:
tensor_a.dtype

torch.int64

In [6]:
tensor_a * 100
tensor_a

tensor([0, 1, 2, 3, 4])

In [7]:
torch.multiply(tensor_a, 100)
tensor_a

tensor([0, 1, 2, 3, 4])

In [8]:
torch.multiply(tensor_a, torch.arange(5))
tensor_a

tensor([0, 1, 2, 3, 4])

In [9]:
tensor_b = torch.tensor(1,2,3,4,5)
tensor_b

TypeError: tensor() takes 1 positional argument but 5 were given

In [10]:
tensor_b = torch.tensor_split(tensor_a)
tensor_b

TypeError: tensor_split() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, tuple of ints indices, int dim)
 * (Tensor input, Tensor tensor_indices_or_sections, int dim)
 * (Tensor input, int sections, int dim)
