In [ ]:
  # Numpy is a special kind of array. It allows to store anything of different types of data.
# Numpy- Numeric Python
# Anything in the Numpy array must be of the same datatype
# ndarray = n-dimensional array

1

In [ ]:
list1 = ['Sid', 0, list, 90, 'huh', True]
list1[0]

'Sid'

In [5]:
import numpy as np

In [ ]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1,np1[5], np1[6]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 5, 6)

In [ ]:
np1.shape

(10,)

In [ ]:
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Step
np3 = np.arange(0,20,2)
np3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Array of zeroes
np4 = np.zeros(5)
np4

array([0., 0., 0., 0., 0.])

In [ ]:
# Multidimensional zeroes
np5 = np.zeros((2,5))
np5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Full Array
np6 = np.full((10), 7)
np6

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [ ]:
# Multidimensional full array
np7 = np.full((3,10), 9)
np7

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [ ]:
# Converting array into a numpy
list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
np8 = np.array(list)
np8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np8[7]

7

In [ ]:
# Slicing Numpy arrays
# Returning 4,5,6,7
np8[4:8]            # Learn--> starting from x Upto but not including y. Starting from 4 but not including 8

array([4, 5, 6, 7])

In [ ]:
# Slice and return something till the end--> from 12
np8[12:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np8[-3:-1]              #smaller: #larger

array([18, 19])

In [ ]:
# Slice in steps
np8[3:17:2]

array([ 3,  5,  7,  9, 11, 13, 15])

In [ ]:
# Return entire attay in steps of 2
np8[::2]
np8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
# pulling from 2-D Array
# np9 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# In numpy, all sub-arrays within a 2D array must have the same length. The above had 9 and 10 elements, so error.

np9 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
np9[1,1]

12

In [ ]:
#Slicing 2-d array
# 4-6
np9[0:1, 3:6]

array([[4, 5, 6]])

In [ ]:
# 15-18
np9[1:2, 4:8]

array([[15, 16, 17, 18]])

In [ ]:
# 2-3 and 12-13
np9[0:2, 1:3]

array([[ 2,  3],
       [12, 13]])

In [ ]:
# Numpy universal functions
np.sqrt(np9)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595]])

In [ ]:
np.square(np9)

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225, 256, 289, 324, 361, 400]])

In [ ]:
np.abs(np9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
np.max(np9)

20

In [ ]:
np.min(np9)

1

In [ ]:
np.sign(np9)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
  # Trigometric values
  np.sin(np9)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
        -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525]])

In [ ]:
np.abs(np.sin(np9))

array([[0.84147098, 0.90929743, 0.14112001, 0.7568025 , 0.95892427,
        0.2794155 , 0.6569866 , 0.98935825, 0.41211849, 0.54402111],
       [0.99999021, 0.53657292, 0.42016704, 0.99060736, 0.65028784,
        0.28790332, 0.96139749, 0.75098725, 0.14987721, 0.91294525]])

In [ ]:
np.cos(np9)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
        -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206]])

In [ ]:
np.abs(np.cos(np9))

array([[0.54030231, 0.41614684, 0.9899925 , 0.65364362, 0.28366219,
        0.96017029, 0.75390225, 0.14550003, 0.91113026, 0.83907153],
       [0.0044257 , 0.84385396, 0.90744678, 0.13673722, 0.75968791,
        0.95765948, 0.27516334, 0.66031671, 0.98870462, 0.40808206]])

In [ ]:
np.tan(np9)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01, -6.79971146e+00, -4.52315659e-01,
         6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
         3.49391565e+00, -1.13731371e+00,  1.51589471e-01,
         2.23716094e+00]])

In [ ]:
np.abs(np.tan(np9))

array([[1.55740772e+00, 2.18503986e+00, 1.42546543e-01, 1.15782128e+00,
        3.38051501e+00, 2.91006191e-01, 8.71447983e-01, 6.79971146e+00,
        4.52315659e-01, 6.48360827e-01],
       [2.25950846e+02, 6.35859929e-01, 4.63021133e-01, 7.24460662e+00,
        8.55993401e-01, 3.00632242e-01, 3.49391565e+00, 1.13731371e+00,
        1.51589471e-01, 2.23716094e+00]])

In [ ]:
np.exp(np9)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03, 2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08, 4.85165195e+08]])

In [ ]:
# Copy vs. View
np10 = np.copy(np9)
np10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
np10 [1,2] =  32

In [ ]:
np9

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 32, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
np10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 32, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
# Shape and reshape numpy arrays
np10 = np9.reshape(5,4)

In [ ]:
np10

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [32, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
np9 = np9.reshape(10,2)
np9.shape

(10, 2)

In [ ]:
np9 = np9.reshape(2, 5, 2)
np9

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [ ]:
np9 = np9.reshape(-20)
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
np9

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#Iterating through Numpy arrays
for x in np9:
  print (x)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]
[11 12]
[13 14]
[15 16]
[17 18]
[19 20]


In [ ]:
for x in np9:
  for y in x:
    print(y)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
for x in np9:
  print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [ ]:
np9

for x in np9:
  for y in x:
    for z in y:
      print(z)


In [ ]:
for x in np.nditer(np9):
  print(x)

In [ ]:
#Sorting Numpy arrays
np11 = np.array([324,564,6534,64,42,45, 2, 5,34343, 3434,2, 434, 4343, 21, 98, 0 , 787 ,76, 54545, 67676767])
np11 = np.sort(np11)
np11


array([       0,        2,        2,        5,       21,       42,
             45,       64,       76,       98,      324,      434,
            564,      787,     3434,     4343,     6534,    34343,
          54545, 67676767])

In [8]:
np11 = np.array(["a", "A", "c", "D", "Sandeep", "ki", "Maa", "ka", "Bhosada", "Bhen k", "lode", "Randi", "k", "pille"])

In [9]:
print(np11)

['a' 'A' 'c' 'D' 'Sandeep' 'ki' 'Maa' 'ka' 'Bhosada' 'Bhen k' 'lode'
 'Randi' 'k' 'pille']


In [10]:
np.sort(np11)

array(['A', 'Bhen k', 'Bhosada', 'D', 'Maa', 'Randi', 'Sandeep', 'a', 'c',
       'k', 'ka', 'ki', 'lode', 'pille'], dtype='<U7')

In [11]:
np12 = np.array([True, False, False, True, False])
np.sort(np12)

array([False, False, False,  True,  True])

In [14]:
np9


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [19]:
np9 = np9.reshape(5,4)
np9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
np.sort(np9)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])